import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "Level 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <div className="min-h-screen bg-white">
          {children}
        </div>
      </body>
    </html>
  );
}
